package com.jqueenb.dao;

import com.jqueenb.pojo.Order;
import com.jqueenb.pojo.OrderItem;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqueenb_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqueenb_order
     *
     * @mbg.generated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqueenb_order
     *
     * @mbg.generated
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqueenb_order
     *
     * @mbg.generated
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqueenb_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Order record);

    /*
    * 取消订单--查询订单
    * @userid
    * @orderno
    * */
    Order findOrderByUseridAndOrderNo(@Param("userId") Integer userId,
                                      @Param("orderNo") Long orderNo);
    Order findOrderByOrderNo(Long orderNo);
    /*
    * 根据userid查询
    * */
    List<Order> findOrderByUserId(Integer userId);
    /*发货并更新订单状态和时间*/
    int updateStatusAndSendtime(Order order);
}